# Generated by Django 5.0.4 on 2024-04-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
