# Generated by Django 5.0.4 on 2024-04-12 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
